import type {
  FurnitureItem,
  ScenarioTemplate,
  WorkspaceSnapshot,
  WorkspaceState,
} from "./types";

const cloneFurniture = (items: FurnitureItem[]) =>
  items.map((item) => ({ ...item }));

export const scenarioTemplates: ScenarioTemplate[] = [
  {
    id: "bedroom",
    name: "Bedroom circulation",
    shortName: "Bedroom",
    description:
      "Preserve the bed and powered desk while opening a personal route from the door.",
    question: "Can I reach the bed and my desk without giving up what matters?",
    room: {
      width: 480,
      height: 360,
      door: { wall: "bottom", x: 30, width: 95 },
    },
    mobility: {
      deviceLabel: "Wheelchair",
      chairWidth: 72,
      minimumPassage: 90,
      turningDiameter: 150,
      priorities: ["transfer-safety", "fewest-moves", "daily-reach"],
    },
    furniture: [
      {
        id: "bed",
        name: "Bed",
        kind: "bed",
        x: 200,
        y: 30,
        width: 205,
        height: 150,
        rotation: 0,
        locked: true,
        lockReason: "Keep close to the window",
        stabilityCritical: true,
        color: "#D8C7FF",
      },
      {
        id: "dresser",
        name: "Dresser",
        kind: "dresser",
        x: 28,
        y: 178,
        width: 125,
        height: 55,
        rotation: 0,
        locked: false,
        color: "#FFCC91",
      },
      {
        id: "desk",
        name: "Desk",
        kind: "desk",
        x: 335,
        y: 266,
        width: 125,
        height: 60,
        rotation: 0,
        locked: true,
        lockReason: "Power outlet is on this wall",
        color: "#9FE3CF",
      },
      {
        id: "nightstand",
        name: "Nightstand",
        kind: "nightstand",
        x: 414,
        y: 58,
        width: 48,
        height: 48,
        rotation: 0,
        locked: false,
        color: "#FF9CA6",
      },
      {
        id: "chair",
        name: "Desk chair",
        kind: "chair",
        x: 360,
        y: 204,
        width: 54,
        height: 54,
        rotation: 0,
        locked: false,
        color: "#A7C8FF",
      },
    ],
    targets: [
      {
        id: "bed-left",
        label: "Left side of bed",
        objectId: "bed",
        side: "left",
        required: true,
        purpose: "transfer",
        clearanceDepth: 95,
      },
      {
        id: "desk-left",
        label: "Desk workspace",
        objectId: "desk",
        side: "left",
        required: true,
        purpose: "work",
        clearanceDepth: 80,
      },
    ],
    selectedId: "dresser",
  },
  {
    id: "studio",
    name: "Small studio",
    shortName: "Studio",
    description:
      "Create an everyday loop between the entrance, sofa, work table, and storage.",
    question: "Can the room support work, rest, and storage in one clear loop?",
    room: {
      width: 520,
      height: 370,
      door: { wall: "bottom", x: 205, width: 95 },
    },
    mobility: {
      deviceLabel: "Power wheelchair",
      chairWidth: 76,
      minimumPassage: 95,
      turningDiameter: 165,
      priorities: ["transfer-safety", "daylight", "daily-reach"],
    },
    furniture: [
      {
        id: "sofa",
        name: "Sofa bed",
        kind: "sofa",
        x: 26,
        y: 35,
        width: 205,
        height: 92,
        rotation: 0,
        locked: true,
        lockReason: "Morning light and transfer side",
        stabilityCritical: true,
        color: "#D8C7FF",
      },
      {
        id: "work-table",
        name: "Work table",
        kind: "table",
        x: 350,
        y: 42,
        width: 135,
        height: 72,
        rotation: 0,
        locked: true,
        lockReason: "Wall-mounted monitor",
        color: "#9FE3CF",
      },
      {
        id: "wardrobe",
        name: "Wardrobe",
        kind: "wardrobe",
        x: 160,
        y: 202,
        width: 145,
        height: 62,
        rotation: 0,
        locked: false,
        color: "#FFCC91",
      },
      {
        id: "studio-chair",
        name: "Work chair",
        kind: "chair",
        x: 383,
        y: 145,
        width: 54,
        height: 54,
        rotation: 0,
        locked: false,
        color: "#A7C8FF",
      },
      {
        id: "shelf",
        name: "Low shelf",
        kind: "shelf",
        x: 20,
        y: 285,
        width: 150,
        height: 48,
        rotation: 0,
        locked: false,
        color: "#FF9CA6",
      },
    ],
    targets: [
      {
        id: "sofa-right",
        label: "Sofa transfer side",
        objectId: "sofa",
        side: "right",
        required: true,
        purpose: "transfer",
        clearanceDepth: 100,
      },
      {
        id: "table-left",
        label: "Work table",
        objectId: "work-table",
        side: "left",
        required: true,
        purpose: "work",
        clearanceDepth: 85,
      },
      {
        id: "wardrobe-front",
        label: "Wardrobe",
        objectId: "wardrobe",
        side: "bottom",
        required: false,
        purpose: "reach",
        clearanceDepth: 70,
      },
    ],
    selectedId: "wardrobe",
  },
  {
    id: "custom",
    name: "Custom room",
    shortName: "Custom",
    description:
      "Start from a simple room and adapt dimensions, furniture, and personal constraints.",
    question: "What would make this room work for your movement?",
    room: {
      width: 450,
      height: 340,
      door: { wall: "bottom", x: 35, width: 95 },
    },
    mobility: {
      deviceLabel: "Mobility device",
      chairWidth: 70,
      minimumPassage: 90,
      turningDiameter: 150,
      priorities: ["transfer-safety", "fewest-moves"],
    },
    furniture: [
      {
        id: "custom-bed",
        name: "Bed",
        kind: "bed",
        x: 205,
        y: 35,
        width: 200,
        height: 145,
        rotation: 0,
        locked: false,
        color: "#D8C7FF",
      },
      {
        id: "custom-table",
        name: "Table",
        kind: "table",
        x: 255,
        y: 245,
        width: 130,
        height: 65,
        rotation: 0,
        locked: false,
        color: "#9FE3CF",
      },
      {
        id: "custom-chair",
        name: "Chair",
        kind: "chair",
        x: 80,
        y: 180,
        width: 54,
        height: 54,
        rotation: 0,
        locked: false,
        color: "#A7C8FF",
      },
    ],
    targets: [
      {
        id: "custom-bed-left",
        label: "Bed approach",
        objectId: "custom-bed",
        side: "left",
        required: true,
        purpose: "transfer",
        clearanceDepth: 95,
      },
    ],
    selectedId: "custom-bed",
  },
];

export function getScenario(id: string) {
  return (
    scenarioTemplates.find((scenario) => scenario.id === id) ??
    scenarioTemplates[0]
  );
}

export function buildWorkspace(
  scenarioId = "bedroom",
  timestamp = new Date().toISOString(),
): WorkspaceState {
  const scenario = getScenario(scenarioId);
  const furniture = cloneFurniture(scenario.furniture);
  const snapshot: WorkspaceSnapshot = {
    id: "baseline",
    label: `${scenario.shortName} baseline`,
    createdAt: timestamp,
    scenarioId: scenario.id,
    scenarioName: scenario.name,
    question: scenario.question,
    room: { ...scenario.room, door: { ...scenario.room.door } },
    furniture: cloneFurniture(furniture),
    mobility: {
      ...scenario.mobility,
      priorities: [...scenario.mobility.priorities],
    },
    targets: scenario.targets.map((target) => ({ ...target })),
    activeTargetId: scenario.targets[0]?.id ?? "",
  };

  return {
    version: 2,
    scenarioId: scenario.id,
    scenarioName: scenario.name,
    question: scenario.question,
    room: { ...scenario.room, door: { ...scenario.room.door } },
    furniture,
    mobility: {
      ...scenario.mobility,
      priorities: [...scenario.mobility.priorities],
    },
    targets: scenario.targets.map((target) => ({ ...target })),
    activeTargetId: scenario.targets[0]?.id ?? "",
    baseline: snapshot,
    history: [],
    activity: [
      {
        id: `activity-${scenario.id}-welcome`,
        actor: "System",
        title: `${scenario.shortName} scenario loaded`,
        detail: scenario.description,
        at: timestamp,
        reversible: false,
      },
    ],
    proposal: null,
    feedback: [],
    showBaseline: false,
    selectedId: scenario.selectedId,
  };
}

export const furniturePresets = [
  {
    kind: "bed" as const,
    name: "Bed",
    width: 200,
    height: 145,
    color: "#D8C7FF",
  },
  {
    kind: "dresser" as const,
    name: "Dresser",
    width: 125,
    height: 55,
    color: "#FFCC91",
  },
  {
    kind: "desk" as const,
    name: "Desk",
    width: 125,
    height: 60,
    color: "#9FE3CF",
  },
  {
    kind: "chair" as const,
    name: "Chair",
    width: 54,
    height: 54,
    color: "#A7C8FF",
  },
  {
    kind: "wardrobe" as const,
    name: "Wardrobe",
    width: 145,
    height: 62,
    color: "#FFCC91",
  },
  {
    kind: "table" as const,
    name: "Table",
    width: 135,
    height: 70,
    color: "#9FE3CF",
  },
  {
    kind: "sofa" as const,
    name: "Sofa",
    width: 205,
    height: 92,
    color: "#D8C7FF",
  },
  {
    kind: "shelf" as const,
    name: "Shelf",
    width: 150,
    height: 48,
    color: "#FF9CA6",
  },
];
